### PR TITLE
Update mypy commit

### PR DESCRIPTION
**Pull request by mr-c**
Includes a change in behavior (a revert commit https://github.com/python/mypy/commit/329e38e6f23c92d6be7c7839d3b44bf7e2b517dc) which will be in the upcoming 1.12 release

### CODE REVIEW

**Comment by cdce8p** [comment]
I was planning to do the next release once the `release-1.12` branch is cut. Do you need another one earlier with this PR?

**Comment by mr-c** [comment]
@cdce8p I was able to find a local workaround, so the need isn't urgent from my side. I'm fine with waiting until the release branch is cut

**Comment by cdce8p** [comment]
> I was planning to do the next release once the `release-1.12` branch is cut.

@mr-c Just pushed a new version `1.12.0b1`. https://github.com/cdce8p/mypy-dev/releases/tag/1.12.0b1

**Comment by mr-c** [comment]
> > I was planning to do the next release once the `release-1.12` branch is cut.
> 
> @mr-c Just pushed a new version `1.12.0b1`. https://github.com/cdce8p/mypy-dev/releases/tag/1.12.0b1
> 
> 

Thank you!

**Pull request closed without merging**
